name: cicd assignment

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    needs: train
    if: ${{ needs.train.result == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker image from registry
        run: docker pull sneharaos26/iisc_assignments:docker-ml-model

      - name: Run Docker container and test
        run: |
          docker run --name ml-container sneharaos26/iisc_assignments:docker-ml-model python3 test.py
          score=$(docker inspect ml-container)
          thresh=0.35
          if [[ $(echo "$score < $thresh" | bc -l) -ne 0 ]]; then echo "Score less than or equal to 0.35. Failure!" && exit 1; fi

