name: cicd assignment

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker image from registry
        run: docker pull sneharaos26/iisc_assignments:docker-ml-model

      - name: Run Docker container and test
        run: |
# docker run --name ml-container sneharaos26/iisc_assignments:docker-ml-model python3 test.py
          score=$(docker run --name ml-container sneharaos26/iisc_assignments:docker-ml-model python3 test.py)
          echo $score
          if [[ `echo "score 0.35" | awk '{print ($1 < $2)}'` -eq 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
