name: test

on:
  pull_request:
    branches:
      - main

jobs:
  run-and-test:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ needs.train.result == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker image from registry
        run: docker pull sneharaos26/iisc_assignments:docker-ml-model

      - name: Run Docker container and test
        run: |
          docker run --name ml-container docker-ml-model python3 test.py
          score=$(docker inspect ml-container --format='{{index .State.Health.Status}}')
          if [ $(awk 'BEGIN{ print ("'$score'" > 0.50) }') -eq 1 ]; then
            exit 0
          else
            exit 1
          fi